spring:
  datasource:
    url: jdbc:h2:mem:ws2023regionalmod2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /ws2023regionalmod2
